analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    unawaited_futures: ignore
    use_build_context_synchronously: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
