analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    inference_failure_on_instance_creation: ignore
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    unawaited_futures: ignore
    use_build_context_synchronously: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
