name: piton_test_case
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # State Management
  flutter_riverpod: ^2.6.1
  # Navigation
  auto_route: ^9.2.2
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # Responsive UI
  flutter_screenutil: ^5.9.3
  # Network
  dio: ^5.7.0
  # Dependency Injection
  get_it: ^8.0.2
  # UI
  flutter_svg: ^2.0.15
  # Localization
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  # Local Storage
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Manrope Bold
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
    - family: Manrope SemiBold
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf
    - family: Manrope Regular
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
